apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-kubernetes-image
  labels:
    app: docker-kubernetes-image
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-kubernetes-image
  template:
    metadata:
      labels:
        app: docker-kubernetes-image
    spec:
      containers:
        - name: docker-kubernetes-image
          image: ssk1811/docker-kubernetes-image:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: docker-kubernetes-service
spec:
  type: NodePort
  selector:
    app: docker-kubernetes-image
  ports:
    - name: http
      protocol: TCP
      port: 9712
      nodePort: 30443
      targetPort: 8080
